CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_WS2812_WIDGET=y
CONFIG_WS2812_WIDGET_SHOW_LAYER_COLORS=y
CONFIG_WS2812_WIDGET_SHOW_LAYER_CHANGE=y
