include:
  - board: nice_nano//zmk
    shield: HPD_left
    snippet: zmk-usb-logging
  - board: nice_nano//zmk
    shield: HPD_right
    snippet: zmk-usb-logging
  - board: nice_nano//zmk
    shield: settings_reset
